version: "3"
services:
  jenkins:
    build:
      context: ./services
    container_name: jenkins
    volumes:
     - ./services/jenkins/docker.sock:/var/run/docker.sock
     - ./data/jenkins:/var/jenkins_home:rw
     - /data/htdocs:/data/htdocs/:rw
    hostname: jenkins
    restart: always
    ports:
      - "8011:8080"
      - "50000:50000"

networks:
  jenkins:
