version: "3"
services:
  jenkins:
    build:
      context: ./services/jenkins
    container_name: jenkins
    volumes:
     - ./services/jenkins/docker.sock:/var/run/docker.sock
     - ./data/jenkins:/var/jenkins_home:rw
     - /data/htdocs:/data/htdocs/:rw
    hostname: jenkins
    restart: always
    ports:
      - "8011:8080"
      - "50000:50000"

networks:
  jenkins:





version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins'
    container_name: jenkins
    restart: always
    user: root
    ports:
      - '82:8080'
      - '50000:50000'
    volumes:
      - '/var/jenkins_home:/var/jenkins_home'
      - '/usr/local/maven:/usr/local/maven'
      - '/usr/lib/jvm:/usr/lib/jvm'
      - '/usr/share/javazi-1.8:/usr/share/javazi-1.8'
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    privileged: true